apiVersion: apps/v1
kind: Deployment
metadata:
  name: srtappinfradep
  namespace: srtappinfra
spec:
  selector:
  replicas: 1
  template:
    spec:
      containers:
        - name: srtinfraapicontainer
          envFrom:
            - secretRef:
                name: secret
