namePrefix: dev-

resources:
  - ../../base

patchesJson6902:
  - target:
      version: v1 # apiVersion
      kind: Deployment
      name: srtappinfradep
    path: dep-patch.yaml
  - target:
      version: v1beta1 # apiVersion
      kind: ExternalSecret
      name: dev-azure-kv-713-test
    path: externalsecrets-patch.yaml

images:
  - name: jenkinspipeline12/srtinfra
    newName: twilightitsolutions/srtinfra
    newTag: "v1"
  - name: srtserver.azurecr.io/srtappgateway
    newName: srtserver.azurecr.io/srtappgateway
    newTag: "integration_10_dev"
