namePrefix: dev-

secretGenerator:
  - name: secret
    namespace: srtappinfra
    env: secret.properties

resources:
  - ../../base

patchesJson6902:
  - target:
      version: v1 # apiVersion
      kind: Deployment
      name: srtappinfradep
    path: dep-patch.yaml

images:
  - name: jenkinspipeline12/srtinfra
    newName: jenkinspipeline12/srtinfra
    newTag: "v4"
  - name: jenkinspipeline12/srtappgateway
    newName: jenkinspipeline12/srtappgateway
    newTag: "v5"
