namePrefix: dev-

secretGenerator:
  - name: secret
    namespace: srt-appinfra-ns
    env: secret.properties

resources:
  - ../../base

patches:
  - target:
      version: v1 # apiVersion
      kind: Deployment
      name: srt-infraapi-dep
    path: infra-dep-patch.yaml

images:
  - name: jenkinspipeline12/srtinfra
    newName: twilightitsolutions/srtinfra
    newTag: "v4"
  - name: srtserver.azurecr.io/srtappgateway
    newName: srtserver.azurecr.io/srtappgateway
    newTag: "integration_10_dev"
