namePrefix: dev-

resources:
  - ../../base

patchesJson6902:
  - target:
      version: v1 # apiVersion
      kind: Deployment
      name: srt-infraapi-dep
    path: infra-dep-patch.yaml
  - target:
      version: v1beta1 # apiVersion
      kind: ExternalSecret
      name: azure-kv-ext-secret # Change this for new env
    path: externalsecrets-patch.yaml
  - target:
      version: v1beta1
      kind: ExternalSecret
      name: dev-azure-acr-secret # Change this for new env
    path: acrsecret-patch.yaml
images:
  - name: jenkinspipeline12/srtinfra
    newName: twilightitsolutions/srtinfra
    newTag: "v9"
  - name: srtserver.azurecr.io/srtappgateway
    newName: srtserver.azurecr.io/srtappgateway
    newTag: "integration_12_dev"
