apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: azure-acr-secret
  namespace: srt-appinfra-ns
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-cluster-secret-store
    namespace: external-secrets
  target:
    name: azure-kv-acr-secret
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      metadata:
        labels:
          mylable: external
        annotations:
          myannotation: external
      data:
        .dockerconfigjson: "{{ .dockerconfigjson }}"
  data:
    - secretKey: dockerconfigjson
      remoteRef:
        key: acr-secret-value
