apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: azure-acr-secret
  namespace: srt-appinfra-ns
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: dev-azure-cluster-secret-store
    namespace: external-secrets
  target:
    name: azure-kv-acr-secret
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      metadata:
        labels:
          mylable: external
        annotations:
          myannotation: external
      data:
        .dockerconfigjson: "{{.ACR_PASSWORD}}"
  data:
    - secretKey: ACR_PASSWORD
      remoteRef:
        key: ACR-PASSWORD
    - secretKey: ACR_SECRET_NAME
      remoteRef:
        key: ACR-SECRET-NAME
    - secretKey: ACR_SERVER_URL
      remoteRef:
        key: ACR-SERVER-URL
    - secretKey: ACR_USERNAME
      remoteRef:
        key: ACR-USERNAME
