apiVersion: v1
kind: Service
metadata:
  name: srt-appgateway-svc
  namespace: srt-appinfra-ns
spec:
  selector:
    app: srt-appgateway # Should match the labels in your app gateway Deployment
  ports:
    - protocol: TCP
      port: 3000 # The port on which your service will be accessible
      targetPort: 3000 # The port your application listens on
  type: ClusterIP
