apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: config-reader-binding
subjects:
  - kind: ServiceAccount
    name: config-reader-sa
    namespace: srtappinfra
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
