apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: config-reader-binding
subjects:
  - kind: ServiceAccount
    name: config-reader-sa
    namespace: srt-appinfra-ns
roleRef:
  kind: ClusterRole
  name: cluster-reader-and-creator
  apiGroup: rbac.authorization.k8s.io
