apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-cluster-secret-store
  namespace: external-secrets
spec:
  provider:
    azurekv:
      authType: ManagedIdentity
      vaultUrl: https://srt-kv-dev.vault.azure.net/
