apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: azure-kv-713-test
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-cluster-secret-store
    namespace: external-secrets
  target:
    name: azure-kv-ext-secret
  data:
    - secretKey: apikey
      remoteRef:
        key: apikey
    - secretKey: test
      remoteRef:
        key: test
