apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: azure-kv-713-test
  namespace: srt-appinfra-ns
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-cluster-secret-store
    namespace: external-secrets
  target:
    name: azure-kv-ext-secret
  data:
    # - secretKey: apikey
    #   remoteRef:
    #     key: apikey
    # - secretKey: test
    #   remoteRef:
    #     key: test
    - secretKey: ACR_PASSWORD
      remoteRef:
        key: ACR-PASSWORD
    - secretKey: ACR_SECRET_NAME
      remoteRef:
        key: ACR-SECRET-NAME
    - secretKey: ACR_SERVER_URL
      remoteRef:
        key: ACR-SERVER-URL
    - secretKey: ACR_USERNAME
      remoteRef:
        key: ACR-USERNAME
    - secretKey: API_KEY
      remoteRef:
        key: API-KEY
    - secretKey: AWS_EXTERNAL_ID
      remoteRef:
        key: AWS-EXTERNAL-ID
    - secretKey: AWS_REGION
      remoteRef:
        key: AWS-REGION
    - secretKey: AWS_ROLE_TO_ASSUME
      remoteRef:
        key: AWS-ROLE-TO-ASSUME
    - secretKey: AWS_S3_BUCKET_NAME
      remoteRef:
        key: AWS-S3-BUCKET-NAME
    - secretKey: AWS_SESSION_NAME
      remoteRef:
        key: AWS-SESSION-NAME
    - secretKey: AzureWebJobsSecretStorageType
      remoteRef:
        key: AzureWebJobsSecretStorageType
    - secretKey: AzureWebJobsStorage
      remoteRef:
        key: AzureWebJobsStorage
    - secretKey: CALLBACK_URL_ENDPOINT
      remoteRef:
        key: CALLBACK-URL-ENDPOINT
    - secretKey: CLUSTER_INGRESS_URL
      remoteRef:
        key: CLUSTER-INGRESS-URL
    - secretKey: CMF_API_KEY
      remoteRef:
        key: CMF-API-KEY
    - secretKey: CMS_AUTH_KEY
      remoteRef:
        key: CMS-AUTH-KEY
    - secretKey: CMS_ENDPOINT_URL
      remoteRef:
        key: CMS-ENDPOINT-URL
    - secretKey: CMS_TOKEN_VALIDATE_URL
      remoteRef:
        key: CMS-TOKEN-VALIDATE-URL
    - secretKey: CORS_ORIGIN_URL
      remoteRef:
        key: CORS-ORIGIN-URL
    - secretKey: ENVIRONMENT_TYPE
      remoteRef:
        key: ENVIRONMENT-TYPE
    - secretKey: FUNCTIONS_EXTENSION_VERSION
      remoteRef:
        key: FUNCTIONS-EXTENSION-VERSION
    - secretKey: FUNCTIONS_WORKER_RUNTIME
      remoteRef:
        key: FUNCTIONS-WORKER-RUNTIME
    - secretKey: HOSTURL
      remoteRef:
        key: HOSTURL
    - secretKey: IMAGE_NAME
      remoteRef:
        key: IMAGE-NAME
    - secretKey: INFRA_REDIS_ADDRESS
      remoteRef:
        key: INFRA-REDIS-ADDRESS
    - secretKey: INFRA_REDIS_PASSWORD
      remoteRef:
        key: INFRA-REDIS-PASSWORD
    - secretKey: INGRESS_SSL_REDIRECT
      remoteRef:
        key: INGRESS-SSL-REDIRECT
    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: JWT-SECRET-KEY
    - secretKey: LOG_SCHEDULE_TIME_SEC
      remoteRef:
        key: LOG-SCHEDULE-TIME-SEC
    - secretKey: LOG_STORAGE_ACCOUNT_KEY
      remoteRef:
        key: LOG-STORAGE-ACCOUNT-KEY
    - secretKey: LOG_STORAGE_ACCOUNT_NAME
      remoteRef:
        key: LOG-STORAGE-ACCOUNT-NAME
    - secretKey: NODE_SELECTOR_ENABLED
      remoteRef:
        key: NODE-SELECTOR-ENABLED
    - secretKey: NOTIFICATION_PORT
      remoteRef:
        key: NOTIFICATION-PORT
    - secretKey: NOTIFY_PATH
      remoteRef:
        key: NOTIFY-PATH
    - secretKey: POD_PER_NODE
      remoteRef:
        key: POD-PER-NODE
    - secretKey: PROXY_REDIS_HOST
      remoteRef:
        key: PROXY-REDIS-HOST
    - secretKey: PROXY_REDIS_PASSWORD
      remoteRef:
        key: PROXY-REDIS-PASSWORD
    - secretKey: PROXY_REDIS_PORT
      remoteRef:
        key: PROXY-REDIS-PORT
    - secretKey: PYTHON_RPC_PORT
      remoteRef:
        key: PYTHON-RPC-PORT
    - secretKey: SPARE_POD_PER_NODE
      remoteRef:
        key: SPARE-POD-PER-NODE
    - secretKey: SPARE_POD_PER_NODE
      remoteRef:
        key: SPARE-POD-PER-NODE
    - secretKey: SRT_WEBAPP_PORT
      remoteRef:
        key: SRT-WEBAPP-PORT
    - secretKey: WEBSITE_CONTENTAZUREFILECONNECTIONSTRING
      remoteRef:
        key: WEBSITE-CONTENTAZUREFILECONNECTIONSTRING
    - secretKey: WEBSITE_CONTENTSHARE
      remoteRef:
        key: WEBSITE-CONTENTSHARE
    - secretKey: WEBSITE_MOUNT_ENABLED
      remoteRef:
        key: WEBSITE-MOUNT-ENABLED
    - secretKey: WEBSITE_RUN_FROM_PACKAGE
      remoteRef:
        key: WEBSITE-RUN-FROM-PACKAGE
