apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: clusterissuer
    nginx.ingress.kubernetes.io/cors-allow-headers: "cmfapikey, apikey, blobFileName, content-type"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: srt-appinfra-ingress
  namespace: srt-appinfra-ns
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /srtinfra/(.*)
            pathType: Prefix
            backend:
              service:
                name: srt-infraapi-svc
                namespace: srt-appinfra-ns
                port:
                  number: 8000
          - path: /srtapp(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: srt-appgateway-svc
                namespace: srt-appinfra-ns
                port:
                  number: 3000
  # tls:
  #   - hosts:
  #       - devcluster.surgeonreview.net
  #     secretName: tlssecret
